### ISSUE TITLE
ValueError: Failed to extract 'next_data' from the response.

### ISSUE THREAD

**Issue by boxter007** [canxin121/Async-Poe-Client#11]
在本机调试得时候没有问题，转移到服务器（境外）上调用create得时候就出现这个错误。版本0.2.

Traceback (most recent call last):
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/async_poe_client/client.py", line 96, in get_basedata
    json_text = re.search(json_regex, text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/code/poe/poe.py", line 19, in sendmessage
    poe_client = await Poe_Client(p_b, former_key).create()
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/async_poe_client/client.py", line 154, in create
    raise e
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/async_poe_client/client.py", line 149, in create
    await self.get_basedata()
  File "/root/anaconda3/envs/ai/lib/python3.10/site-packages/async_poe_client/client.py", line 99, in get_basedata
    raise ValueError("Failed to extract 'next_data' from the response.") from e

**Comment by canxin121** [comment]
现在还会这样?
